-- Basic
require("core.plugins")
require("core.mappings")
require("core.colors")
require("core.config")
-- Plagins
--require('plugins.neotree')
--require('plugins.treesitter')
--require('plugins.lsp')
--require('plugins.cmp')
--require('plugins.mason')
--require('plugins.telescope')
--require('plugins.formatting')
--require('plugins.gitsigns')
--require('plugins.leap')
--require('plugins.helm')
--require('plugins.kube-utils')
